sudo: false
dist: trusty

language: generic
services:
  - docker
cache: ccache

env:
  global:
    # global settings for all jobs
    - ROS_PARALLEL_JOBS=-j1
    - ROS_PARALLEL_TEST_JOBS=-j1
    - VERBOSE_OUTPUT=true
  matrix:
    # Test the target distro.
    - ROS_DISTRO=melodic DOCKER_BASE_IMAGE=debian:stretch
    #- ROS_DISTRO=melodic DOCKER_BASE_IMAGE=ubuntu:artful
    - ROS_DISTRO=melodic DOCKER_BASE_IMAGE=ubuntu:bionic
    # To test backward compatibility for users who build from source.
    #- ROS_DISTRO=lunar DOCKER_BASE_IMAGE=debian:stretch NOT_TEST_INSTALL=true
    #- ROS_DISTRO=lunar DOCKER_BASE_IMAGE=ubuntu:xenial NOT_TEST_INSTALL=true
    #- ROS_DISTRO=kinetic DOCKER_BASE_IMAGE=debian:jessie NOT_TEST_INSTALL=true
    #- ROS_DISTRO=kinetic DOCKER_BASE_IMAGE=ubuntu:xenial NOT_TEST_INSTALL=true
    #- ROS_DISTRO=indigo DOCKER_BASE_IMAGE=ubuntu:trusty NOT_TEST_INSTALL=true

install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci
script:
  - .industrial_ci/travis.sh
